### PR TITLE
Enhance error thrower

### PR DESCRIPTION
**Pull request by ducbm051291**
## What happened 👀

- Update models accessibility
- Re-structure models
- Catch 401 status code and throw unauthenticated
- Update RequestCompletion<T> = (Result<T, NimbleLoyaltyError>) -> Void
- Allow the user to authenticate over (ignore authenticated)

## Insight 📝

- n/a

## Proof Of Work 📹

- n/a

### CODE REVIEW

**Comment by suho** [comment]
@ducbm051291 What doc you are following to define these errors?

**Comment by ducbm051291** [comment]
> @ducbm051291 What doc you are following to define these errors?

I really have no doc to follow, this is just base on my experience 😅

**Comment by suho** [comment]
@ducbm051291 Did you discuss with Huey to have the same approach on both platforms? ([this conversation](https://nimble-co.slack.com/archives/C04QX5BKNG6/p1679912770570559?thread_ts=1679903962.120519&cid=C04QX5BKNG6))

**Comment by ducbm051291** [comment]
> @ducbm051291 Did you discuss with Huey to have the same approach on both platforms? ([this conversation](https://nimble-co.slack.com/archives/C04QX5BKNG6/p1679912770570559?thread_ts=1679903962.120519&cid=C04QX5BKNG6))

yes, we did 👍

**Comment by suho** [comment]
@ducbm051291 Please create a Notion page that list all error cases that you guys decided to add into the SDK, so we can align on both platforms

**Review by suho — APPROVED** [review]

**Pull request merged**
