### PR TITLE
[Chore] Create Sample project integrated SDK

### PR DESCRIPTION
**Pull request by ducbm051291**
## What happened 👀

- Create a Sample project
- Create SDK Podspec
- Install SDK on Sample project using Cocoapods

## Insight 📝

How to integrate:

1. Open terminal
2. Change the directory to SDK folder
3. Run the command `pod install`
4. Change the directory to Sample folder
5. Run the command `pod install`

## Proof Of Work 📹

Screenshot 2023-03-20 at 11 21 45

Screenshot 2023-03-20 at 11 22 00

### CODE REVIEW

**Comment by suho** [comment]
@ducbm051291 Please add insight and pow for this PR

**Comment by ducbm051291** [comment]
> @ducbm051291 Please add insight and pow for this PR

Updated

**Comment by suho** [comment]
@ducbm051291 Please follow https://github.com/Alamofire/Alamofire to setup the structure of the folder. Also please support both Cocoapods and SPM

**Comment by suho** [comment]
@ducbm051291 Please add Gemfile, then we are good with this PR

**Review by suho — APPROVED** [review]

**Pull request merged**
